export interface PillDef {
  slug: string;
  label: string;
  category: string;
}

export const PILL_CATEGORIES = [
  { key: "activities", label: "Activities & Adventures" },
  { key: "play_toys", label: "Play & Toys" },
  { key: "comfort", label: "Comfort & Cuddles" },
  { key: "daily_rituals", label: "Daily Rituals" },
  { key: "food_treats", label: "Food & Treats" },
  { key: "personality", label: "Personality Traits" },
  { key: "favorite_places", label: "Favorite Places" },
  { key: "social", label: "Social Life" },
  { key: "seasonal", label: "Seasonal Fun" },
  { key: "quirks", label: "Quirks & Habits" },
] as const;

export const PILLS: PillDef[] = [
  // Activities & Adventures (12)
  { slug: "long_walks", label: "Long walks", category: "activities" },
  { slug: "hiking", label: "Hiking trails", category: "activities" },
  { slug: "beach_days", label: "Beach days", category: "activities" },
  { slug: "swimming", label: "Swimming", category: "activities" },
  { slug: "car_rides", label: "Car rides", category: "activities" },
  { slug: "camping", label: "Camping", category: "activities" },
  { slug: "running", label: "Running together", category: "activities" },
  { slug: "bike_rides", label: "Bike rides", category: "activities" },
  { slug: "boating", label: "Boating", category: "activities" },
  { slug: "snow_play", label: "Snow play", category: "activities" },
  { slug: "exploring", label: "Exploring new places", category: "activities" },
  { slug: "sunset_walks", label: "Sunset walks", category: "activities" },

  // Play & Toys (11)
  { slug: "tennis_ball", label: "Tennis ball", category: "play_toys" },
  { slug: "frisbee", label: "Frisbee", category: "play_toys" },
  { slug: "tug_of_war", label: "Tug of war", category: "play_toys" },
  { slug: "squeaky_toys", label: "Squeaky toys", category: "play_toys" },
  { slug: "rope_toys", label: "Rope toys", category: "play_toys" },
  { slug: "sticks", label: "Sticks & branches", category: "play_toys" },
  { slug: "puzzle_toys", label: "Puzzle toys", category: "play_toys" },
  { slug: "chew_bones", label: "Chew bones", category: "play_toys" },
  { slug: "plush_friends", label: "Plush friends", category: "play_toys" },
  { slug: "balls", label: "Balls everywhere", category: "play_toys" },
  { slug: "hide_and_seek", label: "Hide and seek", category: "play_toys" },

  // Comfort & Cuddles (11)
  { slug: "snuggles", label: "Snuggle sessions", category: "comfort" },
  { slug: "belly_rubs", label: "Belly rubs", category: "comfort" },
  { slug: "lap_dog", label: "Lap dog life", category: "comfort" },
  { slug: "spooning", label: "Spooning", category: "comfort" },
  { slug: "holding_paws", label: "Holding paws", category: "comfort" },
  { slug: "forehead_kisses", label: "Forehead kisses", category: "comfort" },
  { slug: "blanket_burrowing", label: "Blanket burrowing", category: "comfort" },
  { slug: "chest_naps", label: "Chest naps", category: "comfort" },
  { slug: "back_scratches", label: "Back scratches", category: "comfort" },
  { slug: "being_carried", label: "Being carried", category: "comfort" },
  { slug: "leaning_on_you", label: "Leaning on you", category: "comfort" },

  // Daily Rituals (11)
  { slug: "morning_stretches", label: "Morning stretches", category: "daily_rituals" },
  { slug: "breakfast_time", label: "Breakfast time", category: "daily_rituals" },
  { slug: "welcome_home", label: "The welcome home", category: "daily_rituals" },
  { slug: "evening_walk", label: "Evening walk", category: "daily_rituals" },
  { slug: "bedtime_routine", label: "Bedtime routine", category: "daily_rituals" },
  { slug: "coffee_companion", label: "Coffee companion", category: "daily_rituals" },
  { slug: "wfh_buddy", label: "Work from home buddy", category: "daily_rituals" },
  { slug: "mail_time", label: "Mail time excitement", category: "daily_rituals" },
  { slug: "window_watching", label: "Watching out the window", category: "daily_rituals" },
  { slug: "doorbell_bark", label: "Doorbell barking", category: "daily_rituals" },
  { slug: "post_walk_nap", label: "Post-walk nap", category: "daily_rituals" },

  // Food & Treats (11)
  { slug: "treat_obsessed", label: "Treat obsessed", category: "food_treats" },
  { slug: "peanut_butter", label: "Peanut butter", category: "food_treats" },
  { slug: "cheese", label: "Cheese please", category: "food_treats" },
  { slug: "banana", label: "Banana lover", category: "food_treats" },
  { slug: "ice_cream", label: "Ice cream licks", category: "food_treats" },
  { slug: "puppuccino", label: "Puppuccino", category: "food_treats" },
  { slug: "birthday_cake", label: "Birthday cake", category: "food_treats" },
  { slug: "carrots", label: "Carrot cruncher", category: "food_treats" },
  { slug: "watermelon", label: "Watermelon", category: "food_treats" },
  { slug: "begging", label: "Begging at dinner", category: "food_treats" },
  { slug: "food_bowl_dance", label: "Food bowl dance", category: "food_treats" },

  // Personality Traits (11)
  { slug: "old_soul", label: "Old soul", category: "personality" },
  { slug: "goofball", label: "Total goofball", category: "personality" },
  { slug: "gentle_giant", label: "Gentle giant", category: "personality" },
  { slug: "firecracker", label: "Little firecracker", category: "personality" },
  { slug: "stubborn_sweetie", label: "Stubborn sweetie", category: "personality" },
  { slug: "velcro_dog", label: "Velcro dog", category: "personality" },
  { slug: "independent", label: "Independent spirit", category: "personality" },
  { slug: "drama_royalty", label: "Drama queen/king", category: "personality" },
  { slug: "protector", label: "The protector", category: "personality" },
  { slug: "social_butterfly", label: "Social butterfly", category: "personality" },
  { slug: "shy_sweetheart", label: "Shy sweetheart", category: "personality" },

  // Favorite Places (12)
  { slug: "the_couch", label: "The couch", category: "favorite_places" },
  { slug: "your_bed", label: "Your bed", category: "favorite_places" },
  { slug: "backyard", label: "The backyard", category: "favorite_places" },
  { slug: "under_table", label: "Under the table", category: "favorite_places" },
  { slug: "sunny_spots", label: "Sunny spots", category: "favorite_places" },
  { slug: "kitchen_floor", label: "The kitchen floor", category: "favorite_places" },
  { slug: "dog_park", label: "Dog park", category: "favorite_places" },
  { slug: "the_car", label: "The car", category: "favorite_places" },
  { slug: "front_porch", label: "Front porch", category: "favorite_places" },
  { slug: "fireplace", label: "By the fireplace", category: "favorite_places" },
  { slug: "the_garden", label: "The garden", category: "favorite_places" },
  { slug: "their_bed", label: "Their own bed", category: "favorite_places" },

  // Social Life (11)
  { slug: "park_friends", label: "Dog park friends", category: "social" },
  { slug: "sibling_love", label: "Sibling love", category: "social" },
  { slug: "grandmas_fave", label: "Grandma's favorite", category: "social" },
  { slug: "neighbor_friend", label: "Neighbor's friend", category: "social" },
  { slug: "kids_bestie", label: "Kids' best friend", category: "social" },
  { slug: "cat_friend", label: "Cat friend", category: "social" },
  { slug: "the_mailman", label: "The mailman", category: "social" },
  { slug: "daycare", label: "Daycare adventures", category: "social" },
  { slug: "play_dates", label: "Play dates", category: "social" },
  { slug: "the_greeter", label: "Being the greeter", category: "social" },
  { slug: "strangers_fave", label: "Strangers' favorite", category: "social" },

  // Seasonal Fun (11)
  { slug: "fall_leaves", label: "Fall leaves", category: "seasonal" },
  { slug: "snow_zoomies", label: "Snow zoomies", category: "seasonal" },
  { slug: "puddle_jumping", label: "Puddle jumping", category: "seasonal" },
  { slug: "spring_flowers", label: "Spring flowers", category: "seasonal" },
  { slug: "sprinklers", label: "Summer sprinklers", category: "seasonal" },
  { slug: "holiday_photos", label: "Holiday photos", category: "seasonal" },
  { slug: "pumpkin_season", label: "Pumpkin season", category: "seasonal" },
  { slug: "christmas_morning", label: "Christmas morning", category: "seasonal" },
  { slug: "rain_dancing", label: "Rain dancing", category: "seasonal" },
  { slug: "autumn_hikes", label: "Autumn hikes", category: "seasonal" },
  { slug: "beach_summer", label: "Beach summer", category: "seasonal" },

  // Quirks & Habits (11)
  { slug: "head_tilt", label: "The head tilt", category: "quirks" },
  { slug: "zoomies", label: "Zoomies", category: "quirks" },
  { slug: "tail_chasing", label: "Tail chasing", category: "quirks" },
  { slug: "side_eye", label: "The side eye", category: "quirks" },
  { slug: "sleeping_upside_down", label: "Sleeping upside down", category: "quirks" },
  { slug: "bed_hogger", label: "Hogging the bed", category: "quirks" },
  { slug: "toy_hoarder", label: "Toy hoarding", category: "quirks" },
  { slug: "army_crawl", label: "The army crawl", category: "quirks" },
  { slug: "talking_back", label: "Talking back", category: "quirks" },
  { slug: "dream_running", label: "Dream running", category: "quirks" },
  { slug: "butt_wiggles", label: "Butt wiggles", category: "quirks" },
];

// Day -> compatible categories (used for resolving pill illustrations)
export const DAY_CATEGORIES: Record<number, string[]> = {
  1: ["comfort", "personality"],
  2: ["daily_rituals", "comfort"],
  3: ["quirks", "personality"],
  4: ["food_treats", "play_toys"],
  5: ["personality", "quirks"],
  6: ["comfort", "daily_rituals"],
  7: ["activities", "comfort"],
  8: ["daily_rituals", "favorite_places"],
  9: ["activities", "favorite_places"],
  10: ["comfort", "favorite_places"],
  11: ["social", "personality"],
  12: ["activities", "daily_rituals"],
  13: ["daily_rituals", "food_treats"],
  14: ["activities", "comfort"],
  15: ["personality", "quirks"],
  16: ["quirks", "play_toys"],
  17: ["social", "activities"],
  18: ["play_toys", "activities"],
  19: ["comfort", "daily_rituals"],
  20: ["activities", "seasonal"],
  21: ["social", "personality"],
  22: ["play_toys", "comfort"],
  23: ["activities", "favorite_places"],
  24: ["comfort", "personality"],
  25: ["comfort", "daily_rituals"],
  26: ["personality", "quirks"],
  27: ["daily_rituals", "food_treats", "favorite_places"],
  28: ["personality", "quirks"],
  29: ["comfort", "daily_rituals"],
  30: ["activities", "comfort"],
};
